# install.packages('devtools')
# require(devtools)
# install_version("statnet", version = "2016.9", repos = "http://cran.us.r-project.org")

install.packages('statnet')
install.packages('tnet')
install.packages('vegan')
install.packages('FastKNN')
install.packages('kableExtra')
install.packages('ggraph')
install.packages('GGally')
